language: android
 
android:
  components:
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-26.0.1

    # The SDK version used to compile your project
    - android-24

    # Additional components
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-22
    - sys-img-armeabi-v7a-android-17
  licenses:
    - '.+'

sudo: required
jdk: oraclejdk8
    
script: 
  - sudo apt-get update && sudo apt-get install oracle-java8-installer
  - java -version

before_script:
  - chmod +x gradlew

script:
  - ./gradlew assembleDebug --stacktrace

