language: android
sudo: required
jdk: oraclejdk8
 
android:
  components:
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-26.0.1

    # The SDK version used to compile your project
    - android-24

    # Additional components
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-22
    - sys-img-armeabi-v7a-android-17
  licenses:
    - '.+'

before_script:
  - chmod +x gradlew

install:
  - echo yes | sdkmanager "tools"
  - echo yes | sdkmanager "platforms;android-25" # Latest platform required by SDK tools
  - echo yes | sdkmanager "extras;android;m2repository"
  - echo yes | sdkmanager "extras;google;m2repository"
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
  # Show version and download Gradle Wrapper if it's not already cached
  - ./gradlew --version
  # Check components status
  - sdkmanager --list || true


script:
  - sudo apt-get update && sudo apt-get install oracle-java8-installer
  - java -version
  # Clean project and download missing dependencies and components
  - ./gradlew assembleDebug --stacktrace
  - ./gradlew test --continue
